### ISSUE TITLE
FNE005 False Positive on Magic Methods

### ISSUE THREAD

**Issue by erikvanderwerf** [Melevir/flake8-functions-names#8]
Magic/dunder methods such as `__exit__(self, exc_type, exc_val, exc_tb) -> bool` and `__contains__(self, x) -> bool` raise a FNE005 that is impossible to fix, and I don't want to add #noqa lines to these methods.

**Comment by Melevir** [comment]
Thanks for the report!

Fixed, try version 0.0.7.

If I forgot some buildin dunder methods, that returns bool, feel free to reopen the issue and add them here: https://github.com/Melevir/flake8-functions-names/blob/main/flake8_functions_names/words.py#L1
